### ISSUE TITLE
No "good titles" saved in SatoshiPay API

### ISSUE THREAD

**Issue by zechendorf** [zechendorf/satoshipay#12]
> im backend kommen auf einmal auch keine titles mehr an (beim ersten test ging es). siehe screenshot.

![screenshot from 2016-07-22 21-24-35](https://cloud.githubusercontent.com/assets/11517177/17077127/0f5d0400-50c5-11e6-804e-b908163208e5.png)

**Comment by zechendorf** [comment]
@meinharrd - I can't reproduce this one. Could it be that you just defined the header of the plugin (which is rendered as ``<h2>`` in the frondend) and not of the good itself?

## Screenshot Plugin Header

![bildschirmfoto vom 2016-07-23 11 06 30](https://cloud.githubusercontent.com/assets/11517177/17077135/91821024-50c5-11e6-83de-50d48b916508.png)

## Screenshot Good Title

![bildschirmfoto vom 2016-07-23 11 06 46](https://cloud.githubusercontent.com/assets/11517177/17077138/96b92e92-50c5-11e6-8f6b-915efb594035.png)

**Comment by zechendorf** [comment]
It was just as I guessed.

**Comment by meinharrd** [comment]
oops, i missed this one, sorry. glad it was a "pebkac" issue ;)

**Comment by zechendorf** [comment]
No problem... ;-)
